### ISSUE TITLE
Listener problem

### ISSUE THREAD

**Issue by hearsilent** [blipinsk/StaggeredAnimationGroup#2]
Can I get end of anim event?

**Comment by blipinsk** [comment]
Yep. You can [`setOnTransitionPreparedListener`](https://github.com/blipinsk/StaggeredAnimationGroup/blob/eed8a3dee5c991e30acd901447657df366484221/staggeredanimationgroup/src/main/java/com/bartoszlipinski/constraint/StaggeredAnimationGroup.java#L185) on the group.

In the callback you will get the `TransitionSet` to which you can [add your own `TransitionListener`](https://developer.android.com/reference/android/support/transition/TransitionSet.html#addListener(android.support.transition.Transition.TransitionListener)).
